plugins {
    id 'java'
}

group = 'net.magnaqore'
version = '0.1.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
    maven { url = 'https://repo.papermc.io/repository/maven-public/' }
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:26.2.build.116-stable'
    compileOnly 'net.luckperms:api:5.4'
}

processResources {
    filesMatching('plugin.yml') {
        expand(version: project.version)
    }
}

jar {
    archiveBaseName = 'MagnaQoreCore'
}
